In [3]:
import numpy as np

In [4]:
# Orthogonal states
ket0 = np.matrix([[1],[0]])
bra0 = ket0.H
ket1 = np.matrix([[0],[1]])
bra1 = ket1.H
ket_plus = 1/np.sqrt(2)*(ket0 + ket1)
ket_minus = 1/np.sqrt(2)*(ket0 - ket1)
ket00 = np.kron(ket0,ket0)
ket01 = np.kron(ket0,ket1)
ket10 = np.kron(ket1,ket0)
ket11 = np.kron(ket1,ket1)

In [5]:
X = ket0 * bra1 + ket1 * bra0

In [6]:
X

matrix([[0, 1],
        [1, 0]])

In [7]:
Y = (-1j * ket0 * bra1) + (1j * ket1 * bra0)

In [8]:
Y

matrix([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]])

In [9]:
Z = ket0 * bra0 - ket1 * bra1

In [10]:
Z

matrix([[ 1,  0],
        [ 0, -1]])

In [11]:
H = 1/np.sqrt(2) * np.matrix([[1,1], [1,-1]])

In [12]:
H

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [13]:
def R_phi(phi):
    return np.matrix([[1,0], [0, (np.e)**(1j*phi)]])

In [14]:
I = np.matrix(np.eye(2)) # I gate

In [15]:
# S gate not its own inverse
# also called sqrt(Z) because SS|q> = Z|q>
S = R_phi(np.pi/2)
S_dagger = R_phi(-np.pi/2)

In [16]:
T = R_phi(np.pi/4)
T_dagger = R_phi(-np.pi/4)

In [17]:
# General U-gates, all single qubit gates are converted into U-gates
def U3(theta, phi, lamb):
    return np.matrix([[np.cos(theta/2),                -np.e**(1j*lamb)*np.sin(theta/2)], 
                      [np.e**(1j*phi)*np.sin(theta/2), np.e**(1j*lamb+1j*phi)*np.cos(theta/2)]])

In [18]:
# U3(0,0,lambda) = U1 = R_phi

In [19]:
def ketgen(vals):
    array = []
    for c in vals:
        if c == '0':
            array.append([0])
        elif c == '1':
            array.append([1])
        else:
            print(f"INVALID VALUE:{c}")
    return np.matrix(array)

In [21]:
print(ketgen("100"))

[[1]
 [0]
 [0]]


In [22]:
def bragen(vals):
    return ketgen(vals).H

In [24]:
print(bragen("0001"))

[[0 0 0 1]]


In [ ]:
np.kron()

In [1]:
SWAP = 1