In [2]:
from importlib import reload  
import numpy as np
import npquantum as npq

In [19]:
npq = reload(npq)

In [8]:
npq.ket10

matrix([[0],
        [0],
        [1],
        [0]])

In [16]:
npq.SWAP * npq.ket10

matrix([[0],
        [1],
        [0],
        [0]])

In [17]:
npq.ket01

matrix([[0],
        [1],
        [0],
        [0]])

In [3]:
npq.pauli_x

matrix([[0, 1],
        [1, 0]])